language: ruby
branches:
  only: master

# For options, look into http://about.travis-ci.org/docs/user/notifications/
notifications:
  email:
    recipients: xixx@spamherelots.com
    on_success: always
    on_failure: always

# Encrypted environment variables: http://about.travis-ci.org/docs/user/encryption-keys/
env:
  global:
    - username="xixx"
    - secure: "DunkA4ADz9O2NErUzGRgmMj+eIDmEMmQWdqMlCZAdZry4TQxHzQo5pXOCEKr\nJtUlrg27JdzngqZ9K7Fo/jvgmykbfFPOnf3qwUohNrsYXVrWs7Zm6mDhKrFm\nZWH8VGZGlUDpMymrfq4107zDePWSl4zrrwtKFtEfFJMkn8No6D8="

script:
  - curl -s https://gist.github.com/xixx/a7c0c6da1c4d93ab968c/raw/publish.sh | bash
